# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSMS_GUI_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1223, 647)
        self.control_bt = QtWidgets.QPushButton(Dialog)
        self.control_bt.setGeometry(QtCore.QRect(390, 530, 261, 28))
        self.control_bt.setObjectName("control_bt")
        self.image_label = QtWidgets.QLabel(Dialog)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 530, 171, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.log_browser = QtWidgets.QTextBrowser(Dialog)
        self.log_browser.setGeometry(QtCore.QRect(390, 570, 261, 31))
        self.log_browser.setObjectName("log_browser")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 570, 171, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.webcam_bt = QtWidgets.QRadioButton(self.layoutWidget)
        self.webcam_bt.setChecked(True)
        self.webcam_bt.setObjectName("webcam_bt")
        self.horizontalLayout_2.addWidget(self.webcam_bt)
        self.video_bt = QtWidgets.QRadioButton(self.layoutWidget)
        self.video_bt.setChecked(False)
        self.video_bt.setObjectName("video_bt")
        self.horizontalLayout_2.addWidget(self.video_bt)
        self.webcam_src_box = QtWidgets.QSpinBox(Dialog)
        self.webcam_src_box.setGeometry(QtCore.QRect(190, 570, 91, 31))
        self.webcam_src_box.setMaximum(5)
        self.webcam_src_box.setObjectName("webcam_src_box")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 530, 91, 31))
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(670, 10, 221, 31))
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(790, 150, 101, 21))
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pitch_browser = QtWidgets.QTextBrowser(Dialog)
        self.pitch_browser.setGeometry(QtCore.QRect(790, 220, 101, 31))
        self.pitch_browser.setObjectName("pitch_browser")
        self.mar_browser = QtWidgets.QTextBrowser(Dialog)
        self.mar_browser.setGeometry(QtCore.QRect(670, 220, 101, 31))
        self.mar_browser.setObjectName("mar_browser")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(670, 110, 131, 31))
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.yaw_browser = QtWidgets.QTextBrowser(Dialog)
        self.yaw_browser.setGeometry(QtCore.QRect(790, 180, 101, 31))
        self.yaw_browser.setObjectName("yaw_browser")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(670, 150, 101, 21))
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.ear_browser = QtWidgets.QTextBrowser(Dialog)
        self.ear_browser.setGeometry(QtCore.QRect(670, 180, 101, 31))
        self.ear_browser.setObjectName("ear_browser")
        self.time_browser = QtWidgets.QTextBrowser(Dialog)
        self.time_browser.setGeometry(QtCore.QRect(290, 570, 91, 31))
        self.time_browser.setObjectName("time_browser")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(290, 530, 91, 31))
        self.label_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.calibration_button = QtWidgets.QPushButton(Dialog)
        self.calibration_button.setGeometry(QtCore.QRect(810, 110, 81, 28))
        self.calibration_button.setObjectName("calibration_button")
        self.ear_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.ear_threshold_bar.setGeometry(QtCore.QRect(670, 340, 151, 16))
        self.ear_threshold_bar.setMaximum(30)
        self.ear_threshold_bar.setPageStep(10)
        self.ear_threshold_bar.setProperty("value", 10)
        self.ear_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.ear_threshold_bar.setObjectName("ear_threshold_bar")
        self.mar_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.mar_threshold_bar.setGeometry(QtCore.QRect(670, 430, 151, 16))
        self.mar_threshold_bar.setMaximum(30)
        self.mar_threshold_bar.setProperty("value", 10)
        self.mar_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.mar_threshold_bar.setObjectName("mar_threshold_bar")
        self.yaw_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.yaw_threshold_browser.setGeometry(QtCore.QRect(830, 520, 51, 31))
        self.yaw_threshold_browser.setObjectName("yaw_threshold_browser")
        self.pitch_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.pitch_threshold_bar.setGeometry(QtCore.QRect(670, 610, 151, 16))
        self.pitch_threshold_bar.setMaximum(30)
        self.pitch_threshold_bar.setProperty("value", 12)
        self.pitch_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.pitch_threshold_bar.setObjectName("pitch_threshold_bar")
        self.drowsiness_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.drowsiness_threshold_browser.setGeometry(QtCore.QRect(1120, 340, 41, 31))
        self.drowsiness_threshold_browser.setObjectName("drowsiness_threshold_browser")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(960, 300, 251, 31))
        self.label_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(670, 390, 281, 31))
        self.label_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.alert_label_1 = QtWidgets.QLabel(Dialog)
        self.alert_label_1.setGeometry(QtCore.QRect(1170, 340, 41, 41))
        self.alert_label_1.setText("")
        self.alert_label_1.setObjectName("alert_label_1")
        self.mar_alert_browser = QtWidgets.QTextBrowser(Dialog)
        self.mar_alert_browser.setGeometry(QtCore.QRect(890, 430, 61, 31))
        self.mar_alert_browser.setObjectName("mar_alert_browser")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(960, 390, 251, 31))
        self.label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.carelessness_yaw_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.carelessness_yaw_threshold_bar.setGeometry(QtCore.QRect(960, 520, 151, 16))
        self.carelessness_yaw_threshold_bar.setMaximum(30)
        self.carelessness_yaw_threshold_bar.setProperty("value", 10)
        self.carelessness_yaw_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.carelessness_yaw_threshold_bar.setObjectName("carelessness_yaw_threshold_bar")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(670, 480, 281, 31))
        self.label_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.alert_label_4 = QtWidgets.QLabel(Dialog)
        self.alert_label_4.setGeometry(QtCore.QRect(1170, 605, 41, 41))
        self.alert_label_4.setText("")
        self.alert_label_4.setObjectName("alert_label_4")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(670, 260, 541, 31))
        self.label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(960, 480, 251, 31))
        self.label_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.carelessness_pitch_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.carelessness_pitch_threshold_browser.setGeometry(QtCore.QRect(1120, 610, 41, 31))
        self.carelessness_pitch_threshold_browser.setObjectName("carelessness_pitch_threshold_browser")
        self.pitch_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.pitch_threshold_browser.setGeometry(QtCore.QRect(830, 610, 51, 31))
        self.pitch_threshold_browser.setObjectName("pitch_threshold_browser")
        self.pitch_alert_browser = QtWidgets.QTextBrowser(Dialog)
        self.pitch_alert_browser.setGeometry(QtCore.QRect(890, 610, 61, 31))
        self.pitch_alert_browser.setObjectName("pitch_alert_browser")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(670, 570, 281, 31))
        self.label_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.yaw_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.yaw_threshold_bar.setGeometry(QtCore.QRect(670, 520, 151, 16))
        self.yaw_threshold_bar.setMaximum(30)
        self.yaw_threshold_bar.setProperty("value", 20)
        self.yaw_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.yaw_threshold_bar.setObjectName("yaw_threshold_bar")
        self.alert_label_3 = QtWidgets.QLabel(Dialog)
        self.alert_label_3.setGeometry(QtCore.QRect(1170, 520, 41, 41))
        self.alert_label_3.setText("")
        self.alert_label_3.setObjectName("alert_label_3")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(960, 570, 251, 31))
        self.label_19.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.alert_label_2 = QtWidgets.QLabel(Dialog)
        self.alert_label_2.setGeometry(QtCore.QRect(1170, 430, 41, 41))
        self.alert_label_2.setText("")
        self.alert_label_2.setObjectName("alert_label_2")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(670, 300, 281, 31))
        self.label_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.ear_alert_browser = QtWidgets.QTextBrowser(Dialog)
        self.ear_alert_browser.setGeometry(QtCore.QRect(890, 340, 61, 31))
        self.ear_alert_browser.setObjectName("ear_alert_browser")
        self.carelessness_yaw_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.carelessness_yaw_threshold_browser.setGeometry(QtCore.QRect(1120, 520, 41, 31))
        self.carelessness_yaw_threshold_browser.setObjectName("carelessness_yaw_threshold_browser")
        self.carelessness_pitch_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.carelessness_pitch_threshold_bar.setGeometry(QtCore.QRect(960, 610, 151, 16))
        self.carelessness_pitch_threshold_bar.setMaximum(30)
        self.carelessness_pitch_threshold_bar.setProperty("value", 10)
        self.carelessness_pitch_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.carelessness_pitch_threshold_bar.setObjectName("carelessness_pitch_threshold_bar")
        self.yawn_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.yawn_threshold_bar.setGeometry(QtCore.QRect(960, 430, 151, 16))
        self.yawn_threshold_bar.setMaximum(30)
        self.yawn_threshold_bar.setProperty("value", 10)
        self.yawn_threshold_bar.setSliderPosition(10)
        self.yawn_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.yawn_threshold_bar.setObjectName("yawn_threshold_bar")
        self.mar_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.mar_threshold_browser.setGeometry(QtCore.QRect(830, 430, 51, 31))
        self.mar_threshold_browser.setObjectName("mar_threshold_browser")
        self.drowsiness_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.drowsiness_threshold_bar.setGeometry(QtCore.QRect(960, 340, 151, 16))
        self.drowsiness_threshold_bar.setMaximum(30)
        self.drowsiness_threshold_bar.setProperty("value", 10)
        self.drowsiness_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.drowsiness_threshold_bar.setObjectName("drowsiness_threshold_bar")
        self.yawn_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.yawn_threshold_browser.setGeometry(QtCore.QRect(1120, 430, 41, 31))
        self.yawn_threshold_browser.setObjectName("yawn_threshold_browser")
        self.yaw_alert_browser = QtWidgets.QTextBrowser(Dialog)
        self.yaw_alert_browser.setGeometry(QtCore.QRect(890, 520, 61, 31))
        self.yaw_alert_browser.setObjectName("yaw_alert_browser")
        self.ear_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.ear_threshold_browser.setGeometry(QtCore.QRect(830, 340, 51, 31))
        self.ear_threshold_browser.setObjectName("ear_threshold_browser")
        self.alert_label_5 = QtWidgets.QLabel(Dialog)
        self.alert_label_5.setGeometry(QtCore.QRect(1170, 190, 41, 41))
        self.alert_label_5.setText("")
        self.alert_label_5.setObjectName("alert_label_5")
        self.face_threshold_browser = QtWidgets.QTextBrowser(Dialog)
        self.face_threshold_browser.setGeometry(QtCore.QRect(1120, 220, 41, 31))
        self.face_threshold_browser.setObjectName("face_threshold_browser")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(960, 110, 251, 31))
        self.label_20.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(960, 180, 201, 31))
        self.label_21.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(960, 150, 251, 23))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.driving_bt = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.driving_bt.setChecked(True)
        self.driving_bt.setObjectName("driving_bt")
        self.horizontalLayout_4.addWidget(self.driving_bt)
        self.no_driving_bt = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.no_driving_bt.setTabletTracking(False)
        self.no_driving_bt.setObjectName("no_driving_bt")
        self.horizontalLayout_4.addWidget(self.no_driving_bt)
        self.face_threshold_bar = QtWidgets.QScrollBar(Dialog)
        self.face_threshold_bar.setGeometry(QtCore.QRect(960, 220, 151, 16))
        self.face_threshold_bar.setMaximum(30)
        self.face_threshold_bar.setProperty("value", 10)
        self.face_threshold_bar.setOrientation(QtCore.Qt.Horizontal)
        self.face_threshold_bar.setObjectName("face_threshold_bar")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(670, 50, 221, 50))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.contour_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.contour_checkbox.setChecked(True)
        self.contour_checkbox.setObjectName("contour_checkbox")
        self.gridLayout.addWidget(self.contour_checkbox, 0, 0, 1, 1)
        self.eye_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.eye_checkbox.setChecked(True)
        self.eye_checkbox.setObjectName("eye_checkbox")
        self.gridLayout.addWidget(self.eye_checkbox, 0, 1, 1, 1)
        self.nose_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.nose_checkbox.setChecked(True)
        self.nose_checkbox.setObjectName("nose_checkbox")
        self.gridLayout.addWidget(self.nose_checkbox, 1, 0, 1, 1)
        self.mouth_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.mouth_checkbox.setChecked(True)
        self.mouth_checkbox.setObjectName("mouth_checkbox")
        self.gridLayout.addWidget(self.mouth_checkbox, 1, 1, 1, 1)
        self.layoutWidget.raise_()
        self.image_label.raise_()
        self.control_bt.raise_()
        self.label_2.raise_()
        self.log_browser.raise_()
        self.layoutWidget.raise_()
        self.webcam_src_box.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.pitch_browser.raise_()
        self.mar_browser.raise_()
        self.label_8.raise_()
        self.yaw_browser.raise_()
        self.label_7.raise_()
        self.ear_browser.raise_()
        self.time_browser.raise_()
        self.label_5.raise_()
        self.calibration_button.raise_()
        self.ear_threshold_bar.raise_()
        self.mar_threshold_bar.raise_()
        self.yaw_threshold_browser.raise_()
        self.pitch_threshold_bar.raise_()
        self.drowsiness_threshold_browser.raise_()
        self.label_12.raise_()
        self.label_16.raise_()
        self.alert_label_1.raise_()
        self.mar_alert_browser.raise_()
        self.label_13.raise_()
        self.carelessness_yaw_threshold_bar.raise_()
        self.label_17.raise_()
        self.alert_label_4.raise_()
        self.label_11.raise_()
        self.label_14.raise_()
        self.carelessness_pitch_threshold_browser.raise_()
        self.pitch_threshold_browser.raise_()
        self.pitch_alert_browser.raise_()
        self.label_18.raise_()
        self.yaw_threshold_bar.raise_()
        self.alert_label_3.raise_()
        self.label_19.raise_()
        self.alert_label_2.raise_()
        self.label_15.raise_()
        self.ear_alert_browser.raise_()
        self.carelessness_yaw_threshold_browser.raise_()
        self.carelessness_pitch_threshold_bar.raise_()
        self.yawn_threshold_bar.raise_()
        self.mar_threshold_browser.raise_()
        self.drowsiness_threshold_bar.raise_()
        self.yawn_threshold_browser.raise_()
        self.yaw_alert_browser.raise_()
        self.ear_threshold_browser.raise_()
        self.alert_label_5.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.layoutWidget_2.raise_()
        self.face_threshold_bar.raise_()
        self.face_threshold_browser.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Focusing Status Monitoring / Face Landmark Detection System"))
        self.control_bt.setText(_translate("Dialog", "Start Cam/Video"))
        self.label_2.setText(_translate("Dialog", "Select Webcam/Video"))
        self.webcam_bt.setText(_translate("Dialog", "Webcam"))
        self.video_bt.setText(_translate("Dialog", "Video"))
        self.label_3.setText(_translate("Dialog", "Webcam SRC"))
        self.label_4.setText(_translate("Dialog", "Select Feature"))
        self.label_6.setText(_translate("Dialog", "Head Pose"))
        self.label_8.setText(_translate("Dialog", "Calculated Value"))
        self.label_7.setText(_translate("Dialog", "EAR/MAR"))
        self.label_5.setText(_translate("Dialog", "Process Time"))
        self.calibration_button.setText(_translate("Dialog", "Calibration"))
        self.label_12.setText(_translate("Dialog", "Drowsiness"))
        self.label_16.setText(_translate("Dialog", "MAR"))
        self.label_13.setText(_translate("Dialog", "Yawn"))
        self.label_17.setText(_translate("Dialog", "YAW"))
        self.label_11.setText(_translate("Dialog", "Threshold(30Frame, about 2Seconds)"))
        self.label_14.setText(_translate("Dialog", "Carelessness(YAW)"))
        self.label_18.setText(_translate("Dialog", "Pitch"))
        self.label_19.setText(_translate("Dialog", "Carelesness(Pitch)"))
        self.label_15.setText(_translate("Dialog", "EAR"))
        self.label_20.setText(_translate("Dialog", "Person Status"))
        self.label_21.setText(_translate("Dialog", "Face Recognition Alert"))
        self.driving_bt.setText(_translate("Dialog", "Focusing"))
        self.no_driving_bt.setText(_translate("Dialog", "Not focusing"))
        self.contour_checkbox.setText(_translate("Dialog", "CONTOUR"))
        self.eye_checkbox.setText(_translate("Dialog", "EYE"))
        self.nose_checkbox.setText(_translate("Dialog", "NOSE"))
        self.mouth_checkbox.setText(_translate("Dialog", "MOUTH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

